spring:
  application:
    name: Application
  security:
    user:
      name: swapnil
      password: Ninja@1Q
      roles: ADMIN
  datasource:
    username: amigoscode
    password: password
    url: jdbc:postgresql://localhost:5432/spring-security
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8080
logging:
  level:
    org.springframework.security: TRACE



